### ISSUE TITLE
关于forward阶段的训练问题

### ISSUE THREAD

**Issue by DaoD** [MaZhiyuanBUAA/Seq2BFforDialogueGeneration#1]
您好，感谢您对Seq2BF的实现，有个细节问题想请教一下。在forward阶段，如何使用到backward阶段生成的信息呢？我看代码里预测时forward_only这个参数设置为True后，表明直接使用上一时刻输入作为下一时刻输出，则backward阶段生成的内容并没有作用于forward阶段呀。

谢谢！

**Comment by MaZhiyuanBUAA** [comment]
前提是你理解测试时的loop function。前向网络的训练数据是完整的qa对，后向网络的训练数据是q和截断倒序的a，两个网络单独训练；测试的时候，后向网络的decoder inputs是_S和key word，一般的seq2seq测试时decoder inputs只有_S，同样正向解码时decoder inputs是_S和逆序的后向的输出

**Comment by DaoD** [comment]
@MaZhiyuanBUAA 谢谢你的及时回复。
这份代码与tf官方的legacy_seq2seq应该比较相近，我有仔细的阅读过。在这个位置
[https://github.com/MaZhiyuanBUAA/Seq2BFforDialogueGeneration/blob/master/seq2seq.py#L333](url)
可以看到，当feed_previous为True的时候，只有第一个decoder_inputs会被用到，也就是你说的_S或者说是GO，反正就是一个开始符。而仔细看rnn_decoder被调用的时候，也就是这个位置[https://github.com/MaZhiyuanBUAA/Seq2BFforDialogueGeneration/blob/master/seq2seq.py#L149](url)，可以看到在解码（预测）时，loop_function不为None，第一个decoder inputs时，恰好prev是None，所以这一条件判断为False，进入之后代码。但当第二个decoder inputs来临时，prev是上一时刻的输出了，所以inp不再是decoder inputs，而使用上一时刻输出作为input，所以尽管你的decoder inputs里包含了backward sequence，解码阶段仍然只会使用第一个输入，也就是_S，其他的都没用上啊。
不知道你有没有理解我的意思？期待你的回复。

**Comment by MaZhiyuanBUAA** [comment]
https://github.com/MaZhiyuanBUAA/Seq2BFforDialogueGeneration/blob/master/seq2seq.py#L851，有判断条件，解码的当前位置大于decoder inputs长度时才会调用loop function，希望对你有帮助

**Comment by DaoD** [comment]
wow, 十分抱歉，你用的是attention_decoder，我看成了rnn_decoder，谢谢你的回复。
还有一个问题是，论文里好像用的是普通的seq2seq，没有使用attention，不知道这个影响大不大？
另外也请问一下你训练出来的这个模型最终生成的质量如何？

**Comment by MaZhiyuanBUAA** [comment]
印象中质量不是很好，主要是基于PMI选的关键字相关性较差。

**Comment by DaoD** [comment]
好的 我在复现这个模型做baseline 谢谢你的帮助

**Comment by MaZhiyuanBUAA** [comment]
不用客气
